apiVersion: v1
kind: Service
metadata:
  name: {{ include "production-cicd-app.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "production-cicd-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
