namespace: production

replicaCount: 2

image:
  repository: swaroopp03/production-cicd-app
  tag: a24493d56a07c7814d009e4c204f2462ef03b0c3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
