knamespace: production

replicaCount: 2

image:
  repository: swaroopp03/production-cicd-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
